### PR TITLE
Fix for rspec 3.3

### PR DESCRIPTION
**Pull request by eitoball**
This PR should fix issue that is discussed in #25. As @myronmarston mentioned:

```
In general, we prefer if extensions limit themselves to our public APIs, as that prevents this kind of issue. What kind of public APIs would you want to no longer have to monkey patch RSpec?
```

We need to this about public APIs and provide some inputs to rspec project.

### CODE REVIEW

**Comment by zephiransas** [comment]
This PR fix the problem for me :+1:

**Comment by mattheworiordan** [comment]
:+1: I have this issue

**Comment by cciollaro** [comment]
:+1: works for me

**Comment by galulex** [comment]
:+1:

**Comment by michaelglass** [comment]
will review this in the next 24 hours, thanks!

**Comment by matthieua** [comment]
Thanks @michaelglass!

**Comment by michaelglass** [comment]
I'm going to split this up into a few different PRs and get it merged...

**Comment by michaelglass** [comment]
moved to #32

**Pull request closed without merging**
